<?php

/*
|--------------------------------------------------------------------------
| Old website addresses -> new pages (301 permanent redirects)
|--------------------------------------------------------------------------
|
| Google and customers still have links to the previous site, e.g.
| https://www.yaraelectronics.com/32-hd-smart-led-tv2. Any address the new site doesn't
| have is looked up here (App\Http\Controllers\Store\LegacyRedirectController).
|
| Targets:
|   sku:MODEL        the product with that model number / SKU (its category if it's hidden)
|   category:slug    a category page
|   route:name       a named page, e.g. route:store.interactivepanels
|   url:/path        any path on this site
|
| Collected from the old store's product API and menus on 30 Sep 2026. Rotatable and double side
| displays point to their own pages since those were added (3 Oct 2026).
*/

return [

    // Old product pages (url_key => new target)
    'products' => [
        'new-98-interactive-panel-with-camera'                              => 'route:store.interactivepanels',
        'new-85-interactive-touch-panel-with-camera'                        => 'route:store.interactivepanels',
        'new-75-interactive-touch-panel-with-camera'                        => 'route:store.interactivepanels',
        'new-75-interactive-touch-panel'                                    => 'route:store.interactivepanels',
        'fully-automatic-commercial-washing-machine'                        => 'route:store.commercialwashers',
        '98-interactive-flat-panel'                                         => 'route:store.interactivepanels',
        '24-digital-podium'                                                 => 'route:store.digitalpodium',
        'new-65-interactive-panel'                                          => 'route:store.interactivepanels',
        'new-65-interactive-touch-panel-with-camera'                        => 'route:store.interactivepanels',
        'yara-centum-100-4k-uhd-smart-led-tv'                               => 'route:store.centum',
        'new-100-qled-google-tv'                                            => 'sku:98SQ25S',
        'new-86-qled-google-tv'                                             => 'sku:85SQ25S',
        'new-55-interactive-panel'                                          => 'route:store.interactivepanels',
        '43-double-side-display'                                            => 'route:store.doublesidedisplay',
        '85-interactive-flat-panel'                                         => 'route:store.interactivepanels',
        'new-75-qled-google-tv-frameless'                                   => 'sku:75SQ25S',
        '65-t-standee-display'                                              => 'route:store.tstandees',
        '24-all-in-one-pcs'                                                 => 'category:commercial-display-solutions',
        '55-t-standee-with-touch-and-camera'                                => 'route:store.tstandees',
        '75-commerical-display'                                             => 'route:store.commercialdisplays',
        '55-t-standee-display'                                              => 'route:store.tstandees',
        '75-interactive-flat-panel'                                         => 'route:store.interactivepanels',
        '65-wallmount-display'                                              => 'route:store.commercialdisplays',
        'new-65-qled-google-tv-frameless'                                   => 'sku:65SQ25S',
        '32-windows-kiosk'                                                  => 'route:store.standalonekiosk',
        '32-andriod-kiosk'                                                  => 'route:store.standalonekiosk',
        '65-interactive-flat-panel'                                         => 'route:store.interactivepanels',
        '43-a-standee-display'                                              => 'route:store.astandees',
        '43-t-standee-display'                                              => 'route:store.tstandees',
        '75uhd-google-smart-tv'                                             => 'sku:75SU23G',
        'new-55-qled-google-tv'                                             => 'sku:55SQ25B',
        '2-ton-5-star-inverter-ac'                                          => 'sku:AS245PD25E',
        '2-ton-3-star-inverter-split-ac-24k'                                => 'sku:AS225BS24E',
        'rotatable-display-with-battries'                                   => 'route:store.rotatabledisplay',
        '32-t-standee'                                                      => 'route:store.tstandees',
        '2-ton-3-star-inverter-split-ac-22k'                                => 'sku:AS243BS25E',
        '55-wallmount-display'                                              => 'route:store.commercialdisplays',
        '32-a-standee-display'                                              => 'route:store.astandees',
        'chillers-4-ton-ac45c25b'                                           => 'route:store.chillers',
        'chillers-4-ton-ac44c26b'                                           => 'route:store.chillers',
        '65-qled-uhd-google-smart-tv'                                       => 'sku:65SQ24G',
        '15-ton-5-star-inverter-ac'                                         => 'sku:AS185PD25E',
        '65uhd-google-smart-tv'                                             => 'sku:65SU23G',
        'chillers-2-ton-ac25c26b'                                           => 'route:store.chillers',
        '1point5-ton-3-star-inverter-split-ac-18k'                          => 'sku:AS183BS25E',
        '1point5-ton-3-star-inverter-split-ac-17k'                          => 'sku:AS183BS24E',
        'chiller-1-ton-ac13c26b'                                            => 'route:store.chillers',
        '101-l-type-standee-display-with-battery'                           => 'route:store.tabletopstandee',
        '1-ton-3-star-inverter-split-ac-12k-m2'                             => 'sku:AS123BS25E',
        '1-ton-5-star-inverter-ac'                                          => 'sku:AS125PD25E',
        '1-ton-3-star-inverter-split-ac-12k'                                => 'sku:AS123BS24E',
        '55uhd-google-smart-tv'                                             => 'sku:55SU23G',
        '43-wallmount-display'                                              => 'route:store.commercialdisplays',
        'industrial-displays'                                               => 'route:store.glassdisplays',
        '50-uhd-smart-led-tv'                                               => 'sku:50SU22MV',
        '10-table-top-digital-standees'                                     => 'route:store.tabletopstandee',
        '8kg-fully-automatic-front-load-washing-machine-black-strip-design' => 'sku:WF80J1GB',
        '7kg-fully-automatic-front-load-washing-machine-black-strip'        => 'sku:WF70J1GB',
        '43-uhd-smart-led-tv'                                               => 'sku:43SU24MV',
        '43-fhd-smart-led-tv'                                               => 'sku:43SF24M',
        '10kg-fully-automatic-top-load-washing-machine-black-strip-design'  => 'sku:WA10K1BS',
        '11kg-semi-automatic-washing-machine'                               => 'sku:WT11K1MT',
        '85kg-fully-automatic-top-load-washing-machine'                     => 'sku:WA85K1BS',
        '75kg-fully-automatic-top-load-washing-machine'                     => 'sku:WA75K1BS',
        '65kg-fully-automatic-top-load-washing-machine-red-flow'            => 'sku:WA65K1RR',
        '65-kg-fully-automatic-top-load-washing-machine-black-strip'        => 'sku:WA65K1BS',
        '65-kg-fully-automatic-top-load-washing-machine'                    => 'sku:WA65K1BR',
        '32-hd-smart-led-tv2'                                               => 'sku:32SH24M',
        '11kg-semi-automatic-washing-machines'                              => 'sku:WT11K1PF',
        '9kg-semi-automatic-top-load-washing-machine-pink-flower'           => 'sku:WT90C1PF',
        '4k-uhd-ptz-camera'                                                 => 'route:store.interactivepanels',
        '32-hd-smart-led-tv1-'                                              => 'sku:32SH22B',
        '102kg-semi-automatic-washing-machine'                              => 'sku:WT10K1MF',
        '102kg-semi-automatic-washing-machines'                             => 'sku:WT10K1TF',
        '8kg-semi-automatic-top-load-washing-machine-blue-lid'              => 'sku:WT80C1BT',
        '8kg-semi-automatic-top-load-washing-machine-black-lid'             => 'sku:WT80W1BT',
        '7kg-semi-automatic-top-load-washing-machine-maroon-lid'            => 'sku:WT70C1MT',
        'twin-tower-multimedia-speakers'                                    => 'route:store.homeaudio',
        '65kg-only-washer-washing-machine'                                  => 'sku:WS65K1PF',
        't23-titan-soundbar-with-8-subwoofer-100w-rms'                      => 'route:store.homeaudio',
        'home-soundbar-with-light-effect'                                   => 'route:store.homeaudio',
        'single-tower-multimedia-speaker'                                   => 'route:store.homeaudio',
    ],

    // Old category, landing and information pages
    'pages' => [
        'televisions'                            => 'category:televisions',
        '4k-google-tv'                           => 'category:google-tv',
        '4k-uhd-smart-led'                       => 'category:smart-tv',
        'fhd-smart-led'                          => 'category:smart-tv',
        'hd-smart-led'                           => 'category:smart-tv',
        '32-hd-smart-led-tvs'                    => 'category:smart-tv',
        'large-screen-display'                   => 'route:store.centum',
        'centum-100-4k-smart-tv'                 => 'route:store.centum',
        'airconditioner'                         => 'category:air-conditioners',
        '1-ton-inverter-ac'                      => 'category:1-ton-ac',
        '15-ton-inverter-ac'                     => 'category:1-5-ton-ac',
        '2-ton-inverter-ac'                      => 'category:2-ton-ac',
        'washing-machine'                        => 'category:washing-machine',
        'fully-automatic'                        => 'category:fully_automatic',
        'semi-automatic'                         => 'category:semi-automatic',
        'only-washer'                            => 'category:only-washer',
        'ifp'                                    => 'route:store.interactivepanels',
        'smart-learning-solution'                => 'route:store.interactivepanels',
        'interactive-touch-displays'             => 'route:store.interactivepanels',
        '55-touch-panel'                         => 'route:store.interactivepanels',
        '65-touch-panel'                         => 'route:store.interactivepanels',
        '75-touch-panel'                         => 'route:store.interactivepanels',
        '85-touch-panel'                         => 'route:store.interactivepanels',
        '98-touch-panel'                         => 'route:store.interactivepanels',
        'b2b'                                    => 'category:commercial-display-solutions',
        'commercial-display-solutions-'          => 'category:commercial-display-solutions',
        'customisable-displays'                  => 'category:commercial-display-solutions',
        'double-side-vertical-displays'          => 'route:store.doublesidedisplay',
        'rotatable-display-with-battery'         => 'route:store.rotatabledisplay',
        'other-products'                         => 'category:commercial-display-solutions',
        '24-all-in-one-pc'                       => 'category:commercial-display-solutions',
        'commerical-display-verticalhorizontal-' => 'route:store.commercialdisplays',
        'digital-commercial-displays'            => 'route:store.commercialdisplays',
        'a-standee'                              => 'route:store.astandees',
        't-standee'                              => 'route:store.tstandees',
        '10-table-top-digital-standee'           => 'route:store.tabletopstandee',
        'kiosk-with-scanner'                     => 'route:store.printingkiosk',
        'digital-podiums'                        => 'route:store.digitalpodium',
        'industrial-display'                     => 'route:store.glassdisplays',
        'single-tower'                           => 'category:single-tower-speakers',
        'twin-tower-multimedia-speaker'          => 'category:twin-tower-speakers',
        'soundbar-with-woofer'                   => 'category:soundbars',
        'page/about-us'                          => 'route:store.about',
        'page/e-waste-management'                => 'route:store.e-waste',
        'page/privacy-policy'                    => 'route:store.privacy',
        'page/shipping-policy'                   => 'route:store.delivery',
        'page/terms-conditions'                  => 'route:store.terms',
        'page/warranty-terms'                    => 'route:store.warranty',
        'page/contact-us'                        => 'route:store.contact',
        'customer/login'                         => 'route:login',
        'customer/register'                      => 'route:register',
    ],

];
